[build]
  functions = "api"
  publish = "."
  command = "echo 'No build step required'"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/slack"
  to = "/.netlify/functions/slack"
  status = 200